export enum ErrorEntity {
  SITEMAP_NOT_FOUND = "sitemap/not-found",
  SITEMAP_INVALID = "sitemap/invalid",
  SITEMAP_ERROR = "sitemap/error",
  RATE_LIMIT_EXCEEDED = "rate-limit/exceeded",
  API_KEY_NOT_FOUND = "api-key/not-found",
  CREDENTIALS_NOT_FOUND = "credentials/not-found",
  UNKNOWN_ERROR = "global/unknown-error",
  USER_NOT_FOUND = "user/not-found",
  USER_NOT_AUTHENTICATED = "user/not-authenticated",
  USER_IS_NOT_ADMIN_OF_ORGANIZATION = "user/is-not-admin-of-organization",
  USER_IS_NOT_MEMBER_OF_ORGANIZATION = "user/is-not-member-of-organization",
  ORGANIZATION_NOT_FOUND = "organization/not-found",
  USER_HAS_NOT_ENOUGH_PLAN_TO_ACCESS_FEATURE = "user/has-not-enough-plan-to-access-feature",
  IP_NOT_FROM_PADDLE = "ip-not-from-paddle",
  ORGANIZATION_HAS_NOT_OWNER = "organization/has-not-owner",
  BILLING_PLAN_NOT_FOUND = "billing-plan/not-found",
}
